import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // === Semantic colors driven by CSS variables — swap automatically in dark mode ===
        primary: {
          DEFAULT: 'var(--c-primary)',
          50: 'var(--c-primary-50)',
          100: 'var(--c-primary-100)',
          200: 'var(--c-primary-200)',
          300: 'var(--c-primary-300)',
          400: 'var(--c-primary-400)',
          500: 'var(--c-primary-500)',
          600: 'var(--c-primary-600)',
          700: 'var(--c-primary-700)',
          800: 'var(--c-primary-800)',
          900: 'var(--c-primary-900)',
        },
        'primary-fixed': 'var(--c-primary-fixed)',
        'primary-fixed-dim': 'var(--c-primary-fixed-dim)',
        'primary-container': 'var(--c-primary-container)',
        'on-primary': 'var(--c-on-primary)',
        'on-primary-fixed': 'var(--c-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--c-on-primary-fixed-variant)',
        'on-primary-container': 'var(--c-on-primary-container)',

        secondary: {
          DEFAULT: 'var(--c-secondary)',
          50: 'var(--c-secondary-50)',
          100: 'var(--c-secondary-100)',
          200: 'var(--c-secondary-200)',
          300: 'var(--c-secondary-300)',
          400: 'var(--c-secondary-400)',
          500: 'var(--c-secondary-500)',
          600: 'var(--c-secondary-600)',
          700: 'var(--c-secondary-700)',
          800: 'var(--c-secondary-800)',
          900: 'var(--c-secondary-900)',
        },
        'secondary-fixed': 'var(--c-secondary-fixed)',
        'secondary-fixed-dim': 'var(--c-secondary-fixed-dim)',
        'secondary-container': 'var(--c-secondary-container)',
        'on-secondary': 'var(--c-on-secondary)',
        'on-secondary-fixed': 'var(--c-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--c-on-secondary-fixed-variant)',
        'on-secondary-container': 'var(--c-on-secondary-container)',

        tertiary: {
          DEFAULT: 'var(--c-tertiary)',
          50: 'var(--c-tertiary-50)',
          100: 'var(--c-tertiary-100)',
          200: 'var(--c-tertiary-200)',
          300: 'var(--c-tertiary-300)',
          400: 'var(--c-tertiary-400)',
          500: 'var(--c-tertiary-500)',
          600: 'var(--c-tertiary-600)',
          700: 'var(--c-tertiary-700)',
          800: 'var(--c-tertiary-800)',
          900: 'var(--c-tertiary-900)',
        },
        'tertiary-fixed': 'var(--c-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--c-tertiary-fixed-dim)',
        'tertiary-container': 'var(--c-tertiary-container)',
        'on-tertiary': 'var(--c-on-tertiary)',
        'on-tertiary-fixed': 'var(--c-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--c-on-tertiary-fixed-variant)',
        'on-tertiary-container': 'var(--c-on-tertiary-container)',

        'surface': 'var(--c-surface)',
        'surface-bright': 'var(--c-surface-bright)',
        'surface-dim': 'var(--c-surface-dim)',
        'surface-variant': 'var(--c-surface-variant)',
        'surface-container-lowest': 'var(--c-surface-container-lowest)',
        'surface-container-low': 'var(--c-surface-container-low)',
        'surface-container': 'var(--c-surface-container)',
        'surface-container-high': 'var(--c-surface-container-high)',
        'surface-container-highest': 'var(--c-surface-container-highest)',
        'surface-glass': 'var(--c-surface-glass)',

        'on-surface': 'var(--c-on-surface)',
        'on-surface-variant': 'var(--c-on-surface-variant)',
        'on-background': 'var(--c-on-background)',

        'outline': 'var(--c-outline)',
        'outline-variant': 'var(--c-outline-variant)',

        error: {
          DEFAULT: 'var(--c-error)',
          50: 'var(--c-error-50)',
          100: 'var(--c-error-100)',
          500: 'var(--c-error-500)',
          600: 'var(--c-error-600)',
          700: 'var(--c-error-700)',
        },
        'error-container': 'var(--c-error-container)',
        'on-error': 'var(--c-on-error)',
        'on-error-container': 'var(--c-on-error-container)',

        'inverse-surface': 'var(--c-inverse-surface)',
        'inverse-on-surface': 'var(--c-inverse-on-surface)',
        'inverse-primary': 'var(--c-inverse-primary)',

        'background': 'var(--c-background)',

        // === Kinetic accent colors (same in both modes) ===
        'kinetic': {
          DEFAULT: '#C1FF72',
          light: '#D4FF8A',
          dim: '#A8E55F',
          dark: '#8FC946',
        },
        'azure': {
          DEFAULT: '#E0F2FE',
          50: '#F0F9FF',
          100: '#E0F2FE',
          200: '#BAE6FD',
          300: '#7DD3FC',
        },
        'terracotta': {
          DEFAULT: '#E2725B',
          light: '#F0A088',
          dim: '#D55E45',
          dark: '#B84A33',
        },

        success: 'var(--c-success)',
        warning: 'var(--c-warning)',
        danger: 'var(--c-error)',
        glass: {
          light: 'rgba(255, 255, 255, 0.08)',
          DEFAULT: 'rgba(255, 255, 255, 0.12)',
          dark: 'rgba(21, 61, 107, 0.45)',
        },

        brand: {
          50: 'var(--c-primary-50)',
          100: 'var(--c-primary-100)',
          200: 'var(--c-primary-200)',
          300: 'var(--c-primary-300)',
          400: 'var(--c-primary-400)',
          500: 'var(--c-primary-500)',
          600: 'var(--c-primary-600)',
          700: 'var(--c-primary-700)',
          800: 'var(--c-primary-800)',
          900: 'var(--c-primary-900)',
          950: 'var(--c-primary-900)',
        },

        bio: {
          success: 'var(--c-success)',
          warning: 'var(--c-warning)',
          danger: 'var(--c-error)',
          neutral: 'var(--c-outline)',
        },

        navy: {
          DEFAULT: 'var(--c-navy)',
          800: 'var(--c-navy)',
          900: 'var(--c-navy)',
        },

        accent: {
          DEFAULT: 'var(--c-primary)',
          400: 'var(--c-primary-400)',
          500: 'var(--c-primary-500)',
          600: 'var(--c-primary-600)',
        },
      },

      fontFamily: {
        sans: ['Montserrat', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Playfair Display', 'Georgia', 'serif'],
        serif: ['Playfair Display', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },

      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-editorial': ['56px', { lineHeight: '64px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'xs': ['0.75rem', { lineHeight: '1rem', fontWeight: '400' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'base': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '500' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        '2xl': ['1.5rem', { lineHeight: '2rem', fontWeight: '600' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem', fontWeight: '700' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem', fontWeight: '700' }],
      },

      spacing: {
        'base': '4px',
        'gutter': '16px',
        'container-margin': '24px',
        'margin-desktop': '64px',
        'xs': '8px',
        'sm': '16px',
        'md': '24px',
        'lg': '40px',
        'xl': '64px',
      },

      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '28px',
        '5xl': '40px',
        'full': '9999px',
      },

      boxShadow: {
        'soft': '0 2px 8px rgba(0, 0, 0, 0.04)',
        'card': '0 4px 12px rgba(0, 0, 0, 0.06)',
        'elevated': '0 8px 32px rgba(0, 0, 0, 0.08)',
        'glass': '0 8px 32px 0 rgba(0, 0, 0, 0.04)',
        'glass-lg': '0 12px 40px 0 rgba(21, 105, 102, 0.10)',
        'glow-brand': '0 0 20px rgba(0, 80, 77, 0.15)',
        'glow-primary': '0 0 12px rgba(21, 105, 102, 0.3)',
        'glow-lime': '0 0 20px rgba(193, 255, 114, 0.3)',
        'glow-blue': '0 0 20px rgba(58, 95, 148, 0.25)',
        'glow-terracotta': '0 0 20px rgba(226, 114, 91, 0.25)',
        'command-glow': '0 0 0 4px rgba(0, 80, 77, 0.05), 0 20px 40px rgba(0, 0, 0, 0.1)',
        'primary-glow': '0 8px 24px rgba(0, 80, 77, 0.20)',
        'dark-card': '0 4px 12px rgba(0, 0, 0, 0.3)',
        'dark-glow': '0 0 24px rgba(0, 80, 77, 0.2)',
        'ambient-teal': '0 20px 50px rgba(21, 105, 102, 0.08)',
        'ambient-blue': '0 20px 50px rgba(58, 95, 148, 0.08)',
        'ambient-warm': '0 20px 50px rgba(226, 114, 91, 0.08)',
        'inner-light': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.4)',
      },

      backgroundImage: {
        'gradient-brand': 'linear-gradient(135deg, #00504d 0%, #156966 100%)',
        'gradient-primary': 'linear-gradient(135deg, #00504d 0%, #156966 100%)',
        'gradient-accent': 'linear-gradient(135deg, #156966 0%, #2d9d99 100%)',
        'gradient-kinetic': 'linear-gradient(135deg, #8ad3cf 0%, #C1FF72 100%)',
        'gradient-blue-azure': 'linear-gradient(135deg, #3a5f94 0%, #6b9adb 100%)',
        'gradient-terracotta': 'linear-gradient(135deg, #E2725B 0%, #f2872c 100%)',
        'gradient-teal-lime': 'linear-gradient(135deg, #00504d 0%, #156966 50%, #C1FF72 100%)',
        'gradient-blue-teal': 'linear-gradient(135deg, #3a5f94 0%, #00504d 100%)',
        'gradient-editorial': 'linear-gradient(135deg, #00504d 0%, #3a5f94 50%, #21B5AF 100%)',
        'gradient-specular': 'linear-gradient(to bottom, rgba(255,255,255,0.20) 0%, transparent 60%)',
        'gradient-dark-surface': 'linear-gradient(180deg, #0e1514 0%, #1b2120 100%)',
        'gradient-dark-card': 'linear-gradient(135deg, #1b2120 0%, #252b2b 100%)',
        'gradient-mesh': 'radial-gradient(at 0% 0%, rgba(138, 211, 207, 0.45) 0px, transparent 50%), radial-gradient(at 100% 0%, rgba(160, 190, 253, 0.35) 0px, transparent 50%), radial-gradient(at 100% 100%, rgba(138, 211, 207, 0.25) 0px, transparent 50%), radial-gradient(at 0% 100%, rgba(255, 182, 145, 0.20) 0px, transparent 50%)',
        'gradient-mesh-subtle': 'radial-gradient(at 0% 0%, rgba(21, 105, 102, 0.05) 0px, transparent 50%), radial-gradient(at 100% 0%, rgba(58, 95, 148, 0.05) 0px, transparent 50%), radial-gradient(at 50% 100%, rgba(0, 80, 77, 0.03) 0px, transparent 50%)',
        'gradient-mesh-dark': 'radial-gradient(at 0% 0%, rgba(87, 218, 211, 0.10) 0px, transparent 50%), radial-gradient(at 100% 0%, rgba(75, 142, 255, 0.08) 0px, transparent 50%), radial-gradient(at 100% 100%, rgba(87, 218, 211, 0.06) 0px, transparent 50%), radial-gradient(at 0% 100%, rgba(255, 183, 131, 0.04) 0px, transparent 50%)',
        'gradient-mesh-dark-subtle': 'radial-gradient(at 0% 0%, rgba(0, 80, 77, 0.12) 0px, transparent 50%), radial-gradient(at 100% 100%, rgba(21, 105, 102, 0.08) 0px, transparent 50%)',
      },

      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'shimmer': 'shimmer 1.5s infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'kinematic': 'kinematicScale 0.8s cubic-bezier(0.16, 1, 0.3, 1) backwards',
        'shimmer-text': 'shimmerText 3s infinite linear',
        'fluid-slide': 'fluidSlide 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'breathe': 'breathe 4s ease-in-out infinite',
        'breathe-soft': 'breatheSoft 5s ease-in-out infinite',
        'breathe-badge': 'breatheBadge 3s ease-in-out infinite',
        'gradient-flow': 'gradientFlow 6s ease infinite',
        'shimmer-sweep': 'shimmerSweep 3s ease-in-out infinite',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'float': 'floatY 4s ease-in-out infinite',
        'float-slow': 'floatYSlow 6s ease-in-out infinite',
        'shine-sweep': 'shineSweep 0.6s ease',
        'wave-expand': 'waveExpand 0.6s ease-out',
        'rotate-slow': 'rotateSlow 20s linear infinite',
        'gradient-text-flow': 'gradientTextFlow 4s ease infinite',
        'pulse-ring': 'pulseRing 2s ease-out infinite',
      },

      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { '0%': { opacity: '0', transform: 'translateY(-12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        pulseGlow: { '0%, 100%': { boxShadow: '0 0 20px rgba(0, 80, 77, 0.15)' }, '50%': { boxShadow: '0 0 30px rgba(0, 80, 77, 0.3)' } },
        kinematicScale: {
          '0%': { transform: 'scale(0.96) translateY(20px)', opacity: '0' },
          '100%': { transform: 'scale(1) translateY(0)', opacity: '1' },
        },
        shimmerText: {
          '0%': { backgroundPosition: '0% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        fluidSlide: {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.02)' },
        },
        breatheSoft: {
          '0%, 100%': { transform: 'scale(1)', boxShadow: '0 8px 32px rgba(21, 105, 102, 0.08)' },
          '50%': { transform: 'scale(1.01)', boxShadow: '0 12px 40px rgba(21, 105, 102, 0.16)' },
        },
        breatheBadge: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.06)', opacity: '0.9' },
        },
        gradientFlow: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        shimmerSweep: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 12px rgba(0, 80, 77, 0.15)' },
          '50%': { boxShadow: '0 0 24px rgba(0, 80, 77, 0.35)' },
        },
        floatY: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        floatYSlow: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        shineSweep: {
          '0%': { left: '-100%' },
          '100%': { left: '150%' },
        },
        waveExpand: {
          '0%': { transform: 'scale(0)', opacity: '0.6' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        rotateSlow: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        gradientTextFlow: {
          '0%, 100%': { backgroundPosition: '0% center' },
          '50%': { backgroundPosition: '100% center' },
        },
        pulseRing: {
          '0%': { transform: 'scale(0.8)', opacity: '0.8' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
      },

      transitionTimingFunction: {
        'smooth-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'elastic': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
} satisfies Config
