/*
# Create core auth and profile tables

1. New Tables
- `usuarios`: custom auth table storing email, password_hash, nombre, rol (paciente/fisioterapeuta).
- `perfiles_simples`: extended profile info for any user (avatar, telefono, fecha_nacimiento).
- `fisioterapeutas_simple`: professional data for fisioterapeuta users (colegiado, especialidad, universidad, anio egreso, certificaciones).
- `tokens_activacion`: activation tokens generated by fisioterapeutas so patients can register.

2. Security
- RLS enabled on all tables.
- Public CRUD policies (TO anon, authenticated) because this app uses a custom auth system
  (password hashing via RPC) and the anon-key frontend must read/write its own data.
- `USING (true)` / `WITH CHECK (true)` is intentional here: the app authenticates against
  the `usuarios` table itself rather than Supabase Auth, so row-level ownership is enforced
  in application logic, not via auth.uid().

3. Notes
- `usuarios.password_hash` stores sha256(password || fixed salt). Never store plaintext.
- `tokens_activacion` tracks who created a token, which patient email it was issued for,
  who consumed it, and when it expires.
*/

CREATE TABLE IF NOT EXISTS usuarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  nombre text NOT NULL,
  rol text NOT NULL CHECK (rol IN ('paciente', 'fisioterapeuta')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_select_usuarios" ON usuarios;
CREATE POLICY "public_select_usuarios" ON usuarios FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_insert_usuarios" ON usuarios;
CREATE POLICY "public_insert_usuarios" ON usuarios FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_usuarios" ON usuarios;
CREATE POLICY "public_update_usuarios" ON usuarios FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_usuarios" ON usuarios;
CREATE POLICY "public_delete_usuarios" ON usuarios FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS perfiles_simples (
  id uuid PRIMARY KEY REFERENCES usuarios(id) ON DELETE CASCADE,
  email text NOT NULL,
  nombre text NOT NULL,
  avatar_url text,
  telefono text,
  fecha_nacimiento date,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE perfiles_simples ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_select_perfiles" ON perfiles_simples;
CREATE POLICY "public_select_perfiles" ON perfiles_simples FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_insert_perfiles" ON perfiles_simples;
CREATE POLICY "public_insert_perfiles" ON perfiles_simples FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_perfiles" ON perfiles_simples;
CREATE POLICY "public_update_perfiles" ON perfiles_simples FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_perfiles" ON perfiles_simples;
CREATE POLICY "public_delete_perfiles" ON perfiles_simples FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS fisioterapeutas_simple (
  id uuid PRIMARY KEY REFERENCES usuarios(id) ON DELETE CASCADE,
  colegiado_id text NOT NULL,
  especialidad_tipo text,
  universidad_egreso text NOT NULL,
  anio_egreso integer NOT NULL,
  certificaciones_adicionales text[] DEFAULT '{}'
);

ALTER TABLE fisioterapeutas_simple ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_select_fisios" ON fisioterapeutas_simple;
CREATE POLICY "public_select_fisios" ON fisioterapeutas_simple FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_insert_fisios" ON fisioterapeutas_simple;
CREATE POLICY "public_insert_fisios" ON fisioterapeutas_simple FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_fisios" ON fisioterapeutas_simple;
CREATE POLICY "public_update_fisios" ON fisioterapeutas_simple FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_fisios" ON fisioterapeutas_simple;
CREATE POLICY "public_delete_fisios" ON fisioterapeutas_simple FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS tokens_activacion (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text UNIQUE NOT NULL,
  created_by uuid REFERENCES usuarios(id),
  fisioterapeuta_id uuid REFERENCES usuarios(id),
  paciente_email text,
  used_by uuid REFERENCES usuarios(id),
  used_at timestamptz,
  expires_at timestamptz NOT NULL,
  is_used boolean DEFAULT false
);

ALTER TABLE tokens_activacion ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_select_tokens" ON tokens_activacion;
CREATE POLICY "public_select_tokens" ON tokens_activacion FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_insert_tokens" ON tokens_activacion;
CREATE POLICY "public_insert_tokens" ON tokens_activacion FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_tokens" ON tokens_activacion;
CREATE POLICY "public_update_tokens" ON tokens_activacion FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_tokens" ON tokens_activacion;
CREATE POLICY "public_delete_tokens" ON tokens_activacion FOR DELETE
  TO anon, authenticated USING (true);
