/*
# New auth schema: profiles, activation_tokens, pacientes_terapeutas

1. New Tables
- `profiles`: unified user table replacing `usuarios` + `perfiles_simples`. Stores id, email, full_name, role, is_active, especialidad, universidad, password_hash. This is the single source of truth for all user data in the frontend.
- `activation_tokens`: 6-digit tokens generated by fisioterapeutas. Stores token, terapeuta_id, diagnostico, is_used.
- `pacientes_terapeutas`: junction table linking patients to their therapists.

2. Security
- RLS enabled on all tables with public CRUD policies (TO anon, authenticated).
- Custom auth system: password hashing done client-side (sha256), ownership enforced in app logic.

3. Notes
- `profiles.role` CHECK constraint allows 'admin', 'fisioterapeuta', 'paciente'.
- `profiles.is_active` defaults to false for patients (must activate via token), true for fisios (set at insert).
- `activation_tokens.token` is a 6-digit string, unique.
- Existing `usuarios` table is kept for backward compat with rutinas/sesiones FKs, but the frontend will ONLY use `profiles`.
- `profiles.password_hash` stores sha256(password || salt), computed client-side.
*/

CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  full_name text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'fisioterapeuta', 'paciente')),
  is_active boolean NOT NULL DEFAULT false,
  especialidad text,
  universidad text,
  password_hash text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_select_profiles" ON profiles;
CREATE POLICY "public_select_profiles" ON profiles FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_insert_profiles" ON profiles;
CREATE POLICY "public_insert_profiles" ON profiles FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_profiles" ON profiles;
CREATE POLICY "public_update_profiles" ON profiles FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_profiles" ON profiles;
CREATE POLICY "public_delete_profiles" ON profiles FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS activation_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text UNIQUE NOT NULL,
  terapeuta_id uuid REFERENCES profiles(id),
  diagnostico text,
  is_used boolean NOT NULL DEFAULT false,
  used_by uuid REFERENCES profiles(id),
  used_at timestamptz,
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE activation_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_select_atokens" ON activation_tokens;
CREATE POLICY "public_select_atokens" ON activation_tokens FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_insert_atokens" ON activation_tokens;
CREATE POLICY "public_insert_atokens" ON activation_tokens FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_atokens" ON activation_tokens;
CREATE POLICY "public_update_atokens" ON activation_tokens FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_atokens" ON activation_tokens;
CREATE POLICY "public_delete_atokens" ON activation_tokens FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS pacientes_terapeutas (
  paciente_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  terapeuta_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (paciente_id, terapeuta_id)
);

ALTER TABLE pacientes_terapeutas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_select_pt" ON pacientes_terapeutas;
CREATE POLICY "public_select_pt" ON pacientes_terapeutas FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_insert_pt" ON pacientes_terapeutas;
CREATE POLICY "public_insert_pt" ON pacientes_terapeutas FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_pt" ON pacientes_terapeutas;
CREATE POLICY "public_delete_pt" ON pacientes_terapeutas FOR DELETE
  TO anon, authenticated USING (true);
